env:
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

window:
  # Spread additional padding evenly around the terminal content.
  padding:
    x: 5
    y: 5
  # Remove buttons
  decorations: buttonless
  # Dimensions if not SimpleFullscreen
  dimensions:
    columns: 140
    lines: 38
  opacity: 1

cursor:
  # Block Underline or Beam
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Block
    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    #blinking: Off

  # Vi mode cursor style
  #
  # If the vi mode cursor style is `None` or not specified, it will fall back to
  # the style of the active value of the normal cursor.
  #
  # See `cursor.style` for available options.
  vi_mode_style: None

  # Cursor blinking interval in milliseconds.
  blink_interval: 750

  # Time after which cursor stops blinking, in seconds.
  #
  # Specifying '0' will disable timeout for blinking.
  blink_timeout: 5

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

  # Thickness of the cursor relative to the cell width as floating point number
  # from `0.0` to `1.0`.
  thickness: 0.15

font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Italic
  # Font size
  size: 14
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

# Gruvbox
colors:
  # Default colors
  primary:
    # hard contrast: background = '#f9f5d7'
    background: '#fbf1c7'
    # soft contrast: background = '#f2e5bc'
    foreground: '#3c3836'

  # Normal colors
  normal:
    black: '#fbf1c7'
    red: '#cc241d'
    green: '#98971a'
    yellow: '#d79921'
    blue: '#458588'
    magenta: '#b16286'
    cyan: '#689d6a'
    white: '#7c6f64'

  # Bright colors
  bright:
    black: '#928374'
    red: '#9d0006'
    green: '#79740e'
    yellow: '#b57614'
    blue: '#076678'
    magenta: '#8f3f71'
    cyan: '#427b58'
    white: '#3c3836'
# tokyo day
# colors:
#   name: TokyoNight Day
#   author: Folke
#   # Default colors
#   primary:
#     background: '0xe1e2e7'
#     foreground: '0x3760bf'

#   # Normal colors
#   normal:
#     black: '0xe9e9ed'
#     red: '0xf52a65'
#     green: '0x587539'
#     yellow: '0x8c6c3e'
#     blue: '0x2e7de9'
#     magenta: '0x9854f1'
#     cyan: '0x007197'
#     white: '0x6172b0'

#   # Bright colors
#   bright:
#     black: '0xa1a6c5'
#     red: '0xf52a65'
#     green: '0x587539'
#     yellow: '0x8c6c3e'
#     blue: '0x2e7de9'
#     magenta: '0x9854f1'
#     cyan: '0x007197'
#     white: '0x3760bf'

#   indexed_colors:
#     - { index: 16, color: '0xb15c00' }
#     - { index: 17, color: '0xc64343' }
      #
# rose-pine-moon
colors:
  primary:
    background: "0xfaf4ed"
    foreground: "0x575279"
  cursor:
    text: "0x575279"
    cursor: "0xcecacd"
  vi_mode_cursor:
    text: "0x575279"
    cursor: "0xcecacd"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: "0x575279"
    background: "0xdfdad9"
  normal:
    black: "0xf2e9e1"
    red: "0xb4637a"
    green: "0x286983"
    yellow: "0xea9d34"
    blue: "0x56949f"
    magenta: "0x907aa9"
    cyan: "0xd7827e"
    white: "0x575279"
  bright:
    black: "0x9893a5"
    red: "0xb4637a"
    green: "0x286983"
    yellow: "0xea9d34"
    blue: "0x56949f"
    magenta: "0x907aa9"
    cyan: "0xd7827e"
    white: "0x575279"
  hints:
    start:
      foreground: "#797593"
      background: "#fffaf3"
    end:
      foreground: "#9893a5"
      background: "#fffaf3"

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When true, selected text will be copied to the primary clipboard
  save_to_clipboard: true

# Login shell with arguments
shell:
  program: /bin/zsh
  args:
    - --login

# Startup directory, unset or None for home directory
working_directory: None

hints:
  enabled:
    - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp\
        :)[^\0-\x1f-<>\"\\s{-}\\^⟨⟩`]+"
      command: open
      post_processing: true
      mouse:
        enabled: true
        mods: Command
      binding:
        key: U
        mods: Command

key_bindings:
  - { key: Slash, mods: Control, chars: "\x1f" }
  - { key: Space, mods: Control, chars: "\0" }
  - { key: Semicolon, mods: Alt, chars: "\e;" }
  # Alt + ;
  - { key: N, mods: Alt, chars: "\en" }
  - { key: L, mods: Alt, chars: "\el" }
  - { key: LBracket, mods: Alt, chars: "\e[" }
  - { key: RBracket, mods: Alt, chars: "\e]" }
  - { key: LBracket, mods: Alt|Shift, chars: "\e{" }
  - { key: RBracket, mods: Alt|Shift, chars: "\e}" }
  - { key: T, mods: Control|Shift, chars: "\e[84;6u" }

import:
 - ~/.config/alacritty/themes/themes/rose-pine-dawn.yaml

