env:
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

window:
  # Spread additional padding evenly around the terminal content.
  padding:
    x: 5
    y: 5
  # Remove buttons
  decorations: buttonless
  # Dimensions if not SimpleFullscreen
  dimensions:
    columns: 140
    lines: 38
  opacity: 1

cursor:
  # Block Underline or Beam
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Block
    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    #blinking: Off

  # Vi mode cursor style
  #
  # If the vi mode cursor style is `None` or not specified, it will fall back to
  # the style of the active value of the normal cursor.
  #
  # See `cursor.style` for available options.
  vi_mode_style: None

  # Cursor blinking interval in milliseconds.
  blink_interval: 750

  # Time after which cursor stops blinking, in seconds.
  #
  # Specifying '0' will disable timeout for blinking.
  blink_timeout: 5

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

  # Thickness of the cursor relative to the cell width as floating point number
  # from `0.0` to `1.0`.
  thickness: 0.15

font:
  normal:
    family: FiraCode Nerd Font
    style: Light
  bold:
    family: FiraCode Nerd Font
    style: SemiBold
  italic:
    family: FiraCode Nerd Font
    style: Light
  # Font size
  size: 12.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 1

# rose-pine-moon
colors:
  primary:
    background: "0xfaf4ed"
    foreground: "0x575279"
  cursor:
    text: "0x575279"
    cursor: "0xcecacd"
  vi_mode_cursor:
    text: "0x575279"
    cursor: "0xcecacd"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: "0x575279"
    background: "0xdfdad9"
  normal:
    black: "0xf2e9e1"
    red: "0xb4637a"
    green: "0x286983"
    yellow: "0xea9d34"
    blue: "0x56949f"
    magenta: "0x907aa9"
    cyan: "0xd7827e"
    white: "0x575279"
  bright:
    black: "0x9893a5"
    red: "0xb4637a"
    green: "0x286983"
    yellow: "0xea9d34"
    blue: "0x56949f"
    magenta: "0x907aa9"
    cyan: "0xd7827e"
    white: "0x575279"
  hints:
    start:
      foreground: "#797593"
      background: "#fffaf3"
    end:
      foreground: "#9893a5"
      background: "#fffaf3"
selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When true, selected text will be copied to the primary clipboard
  save_to_clipboard: true

# Login shell with arguments
shell:
  program: /bin/zsh
  args:
    - --login

# Startup directory, unset or None for home directory
working_directory: None

hints:
  enabled:
    - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp\
        :)[^\0-\x1f-<>\"\\s{-}\\^⟨⟩`]+"
      command: open
      post_processing: true
      mouse:
        enabled: true
        mods: Command
      binding:
        key: U
        mods: Command

key_bindings:
  - { key: Slash, mods: Control, chars: "\x1f" }
  - { key: Space, mods: Control, chars: "\0" }
  - { key: Semicolon, mods: Alt, chars: "\e;" }
  # Alt + ;
  - { key: N, mods: Alt, chars: "\en" }
  - { key: L, mods: Alt, chars: "\el" }
  - { key: LBracket, mods: Alt, chars: "\e[" }
  - { key: RBracket, mods: Alt, chars: "\e]" }
  - { key: LBracket, mods: Alt|Shift, chars: "\e{" }
  - { key: RBracket, mods: Alt|Shift, chars: "\e}" }
  - { key: T, mods: Control|Shift, chars: "\e[84;6u" }
theme: rose-pine-dawn
