env:
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

window:
  # Spread additional padding evenly around the terminal content.
  padding:
    x: 5
    y: 5
  # Remove buttons
  decorations: buttonless
  # Dimensions if not SimpleFullscreen
  dimensions:
    columns: 140
    lines: 38
  opacity: 1

cursor:
  # Block Underline or Beam
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Block
    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    #blinking: Off

  # Vi mode cursor style
  #
  # If the vi mode cursor style is `None` or not specified, it will fall back to
  # the style of the active value of the normal cursor.
  #
  # See `cursor.style` for available options.
  vi_mode_style: None

  # Cursor blinking interval in milliseconds.
  blink_interval: 750

  # Time after which cursor stops blinking, in seconds.
  #
  # Specifying '0' will disable timeout for blinking.
  blink_timeout: 5

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

  # Thickness of the cursor relative to the cell width as floating point number
  # from `0.0` to `1.0`.
  thickness: 0.15

font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Italic
  # Font size
  size: 14
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

#Gruvbox
# colors:
#   # Default colors
#   primary:
#     # hard contrast: background = '#1d2021'
#     background: '#282828'
#     # soft contrast: background = '#32302f'
#     foreground: '#ebdbb2'

#   # Normal colors
#   normal:
#     black: '#282828'
#     red: '#cc241d'
#     green: '#98971a'
#     yellow: '#d79921'
#     blue: '#458588'
#     magenta: '#b16286'
#     cyan: '#689d6a'
#     white: '#a89984'

#   # Bright colors
#   bright:
#     black: '#928374'
#     red: '#fb4934'
#     green: '#b8bb26'
#     yellow: '#fabd2f'
#     blue: '#83a598'
#     magenta: '#d3869b'
#     cyan: '#8ec07c'
#     white: '#ebdbb2'

# Tokyo Nighte
# colors:
#   name: TokyoNight Night
#   author: Folke
#   # Default colors
#   primary:
#     background: '0x1a1b26'
#     foreground: '0xc0caf5'

#   # Normal colors
#   normal:
#     black: '0x15161E'
#     red: '0xf7768e'
#     green: '0x9ece6a'
#     yellow: '0xe0af68'
#     blue: '0x7aa2f7'
#     magenta: '0xbb9af7'
#     cyan: '0x7dcfff'
#     white: '0xa9b1d6'

#   # Bright colors
#   bright:
#     black: '0x414868'
#     red: '0xf7768e'
#     green: '0x9ece6a'
#     yellow: '0xe0af68'
#     blue: '0x7aa2f7'
#     magenta: '0xbb9af7'
#     cyan: '0x7dcfff'
#     white: '0xc0caf5'

#   indexed_colors:
#     - { index: 16, color: '0xff9e64' }
#     - { index: 17, color: '0xdb4b4b' }

# # Rose-Pine
# colors:
#   primary:
#     background: "0x191724"
#     foreground: "0xe0def4"
#   cursor:
#     text: "0xe0def4"
#     cursor: "0x524f67"
#   vi_mode_cursor:
#     text: "0xe0def4"
#     cursor: "0x524f67"
#   line_indicator:
#     foreground: None
#     background: None
#   selection:
#     text: "0xe0def4"
#     background: "0x403d52"
#   normal:
#     black: "0x26233a"
#     red: "0xeb6f92"
#     green: "0x31748f"
#     yellow: "0xf6c177"
#     blue: "0x9ccfd8"
#     magenta: "0xc4a7e7"
#     cyan: "0xebbcba"
#     white: "0xe0def4"
#   bright:
#     black: "0x6e6a86"
#     red: "0xeb6f92"
#     green: "0x31748f"
#     yellow: "0xf6c177"
#     blue: "0x9ccfd8"
#     magenta: "0xc4a7e7"
#     cyan: "0xebbcba"
#     white: "0xe0def4"
#   hints:
#     start:
#       foreground: "#908caa"
#       background: "#1f1d2e"
#     end:
#       foreground: "#6e6a86"
#       background: "#1f1d2e"

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When true, selected text will be copied to the primary clipboard
  save_to_clipboard: true

# Login shell with arguments
shell:
  program: /bin/zsh
  args:
    - --login

# Startup directory, unset or None for home directory
working_directory: None

hints:
  enabled:
    - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp\
        :)[^\0-\x1f-<>\"\\s{-}\\^⟨⟩`]+"
      command: open
      post_processing: true
      mouse:
        enabled: true
        mods: Command
      binding:
        key: U
        mods: Command

key_bindings:
  - { key: Slash, mods: Control, chars: "\x1f" }
  - { key: Space, mods: Control, chars: "\0" }
  - { key: Semicolon, mods: Alt, chars: "\e;" }
  # Alt + ;
  - { key: N, mods: Alt, chars: "\en" }
  - { key: L, mods: Alt, chars: "\el" }
  - { key: LBracket, mods: Alt, chars: "\e[" }
  - { key: RBracket, mods: Alt, chars: "\e]" }
  - { key: LBracket, mods: Alt|Shift, chars: "\e{" }
  - { key: RBracket, mods: Alt|Shift, chars: "\e}" }
  - { key: T, mods: Control|Shift, chars: "\e[84;6u" }

import:
 - ~/.config/alacritty/themes/themes/gruvbox_dark.yaml
