windows:
  - name: sample-three-panes
    root: ~/dev/projects/ruby/liama 
    layout: main-vertical
    panes:
      - vim
      - commands:
        - git pull
        - git status
      - rails server
