# Loading themes before use it
autoload promptinit
fpath=($HOME/.zsh.prompts $fpath)
promptinit

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source $HOME/.dotfiles/scripts/utils.sh

# Customize to your needs...
for config_file (~/.dotfiles/zsh/*.zsh) source $config_file

# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef

setopt RM_STAR_WAIT
setopt CORRECT


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
