# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for config_file (~/.dotfiles/zsh/*.zsh) source $config_file

# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef

setopt RM_STAR_WAIT
setopt CORRECT

source $HOME/.dotfiles/scripts/utils.sh
